### PR TITLE
Presentation holder tests and cleanup

### PR DESCRIPTION
**Pull request by PatStLouis**
A few changes and improvements:
- Added missing presentation holder tests.
- Added self-asserted VC tests.
- Fixed wrong related resource test (duplicate id).
- Updated test numeration with dot values.
- Split up some test statements into separate tests.

### CODE REVIEW

**Review by BigBlueHat — CHANGES_REQUESTED** [review]
So. The file numbering (`411` vs. `4.11`) was deliberate--as strange as it looks. The goal was to get the filesystem sorting to match the spec's sorting. I know it looks weird...but it does work. 😁 

Happy to discuss/debate, though.

**Comment by PatStLouis** [comment]
Untitled
well, if it would have kept the ordering its showing in my vscode ide it would of been better, but it seems like github sorts differently, so I will have to agree with you on this one ;)

**Comment by PatStLouis** [comment]
@BigBlueHat are you okay with the updated numbering?

**Review by BigBlueHat — APPROVED** [review]

**Comment by BigBlueHat** [comment]
> @BigBlueHat are you okay with the updated numbering?

Great work figuring that out! 😁

**Pull request merged**
