### PR TITLE
Add explicit error type to assert.rejects().

### PR DESCRIPTION
**Pull request by BigBlueHat**

### CODE REVIEW

**Review by aljones15 — APPROVED** [review]
This should really be a helper function that like

```js
shouldReject(doc) {
  assert.rejects(endpoints.verify(doc), {name: 'HTTPError'})
}
```

if that is to much of a chore then go ahead and merge and do it later.

**Comment by PatStLouis** [comment]
I agree with @aljones15 , I think these could be bundled in one function

**Review by PatStLouis — APPROVED** [review]

**Comment by BigBlueHat** [comment]
I have to fix some conflicts (as expected), so I'll group this into a function. Good idea. Good call.

**Comment by BigBlueHat** [comment]
@aljones15 @PatStLouis I decided to skip the refactoring for now. Bigger fish to fry and refactoring this was proving more tedious than helpful. We can revisit later.

**Pull request merged**
