### PR TITLE
Add readme section about the `EnvelopingProof` tag usage.

### PR DESCRIPTION
**Pull request by PatStLouis**
This is to partially address the concerns raised in #127.

It's not a requirement to use data integrity to be conformant with this test suite. This test suite doesn't test the securing mechanism, only the data model.

### CODE REVIEW

**Review by aljones15 — APPROVED** [review]
approving, but do remember the `issuer.id` becomes issuer in the actual VC which is relevant as an issuer should not being issuing a VC from another issuer.

**Comment by BigBlueHat** [comment]
> approving, but do remember the `issuer.id` becomes issuer in the actual VC which is relevant as an issuer should not being issuing a VC from another issuer.

@PatStLouis @decentralgabe any thoughts on what you'd expect to see set as `issuer.id` in an enveloping proof scenario? We typically recommend/support `did:key` or HTTP URL values there for the test suites. Thoughts?

**Comment by aljones15** [comment]
> > approving, but do remember the `issuer.id` becomes issuer in the actual VC which is relevant as an issuer should not being issuing a VC from another issuer.
> 
> @PatStLouis @decentralgabe any thoughts on what you'd expect to see set as `issuer.id` in an enveloping proof scenario? We typically recommend/support `did:key` or HTTP URL values there for the test suites. Thoughts?

I believe kid is the issuer: https://w3c.github.io/vc-jose-cose/#jwt-issuer

it should be a did:key for the sake of simplicity and being in line with this test suite.
Not sure how you can get around the alg though which even in the spec is set to eddsa.

**Comment by decentralgabe** [comment]
the semantic layer and securing layer are distinct. the issuer property will stilllbe present after you decode the vc jose cose payload.

**Comment by PatStLouis** [comment]
I would say for envelopes it would be a `did:jwk:`?

**Comment by PatStLouis** [comment]
I will also open a PR on the implementations repo to add the same information.

**Comment by decentralgabe** [comment]
There are no requirements for it to be a did:jwk, did:key, or any other DID method (or controller document URI) would work too.

**Review by brentzundel — APPROVED** [review]

**Comment by aljones15** [comment]
@decentralgabe all other test suites use `did:key` at the moment so that would ensure other implementers at least support the did method used for issuance. We do actually specify only `did:key` for issuer/verificationMethod in some of the other suites although I believe the VC 2.0 suite does not have such a condition set down in it.

**Comment by decentralgabe** [comment]
thanks @aljones15 that makes sense. we can stick to did:jwk in our test suite to make things easier.

**Pull request merged**
