### PR TITLE
Breakup long `type` tests.

### PR DESCRIPTION
**Pull request by BigBlueHat**
- Break up objects w/types list into separate tests.
- Add positive `refreshService.type` test.
- Add positive `credentialSchema.type` test.

### CODE REVIEW

**Comment by PatStLouis** [comment]
At this point why not just use advanced concepts to test this, AFAIK these are already covered:
https://github.com/w3c/vc-data-model-2.0-test-suite/blob/b2bd2dbdad5d810cb7a85c863fdff080381667db/tests/10-vcdm2.js#L969

what's the difference between 
`termsOfUse objects MUST have a type specified.` and 
`Each termsOfUse value MUST specify its type`

**Review by PatStLouis — APPROVED** [review]
I think these could simply be covered by advanced concepts section.

**Comment by BigBlueHat** [comment]
> At this point why not just use advanced concepts to test this, AFAIK these are already covered:
> 
> https://github.com/w3c/vc-data-model-2.0-test-suite/blob/b2bd2dbdad5d810cb7a85c863fdff080381667db/tests/10-vcdm2.js#L969
> 
> what's the difference between `termsOfUse objects MUST have a type specified.` and `Each termsOfUse value MUST specify its type`

There's no difference test-wise, just spec text-wise. I'll make the "Advanced Concepts" ones as skipped and note they are covered earlier.

**Comment by BigBlueHat** [comment]
Actually...the tests are there and work, so I'm going to leave them alone. We can revisit if need be.

**Pull request merged**
